<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="bin\**\*.cs" />
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="CompilerBackend\bin\**\*.cs" />
    <Compile Remove="CompilerBackend\obj\**\*.cs" />
    <Compile Remove="AuroraScript.LanguageServices.Tests\**\*.cs" />
    <Compile Remove="AuroraScript.LanguageServer.Tests\**\*.cs" />
    <EmbeddedResource Remove="bin\**\*" />
    <EmbeddedResource Remove="obj\**\*" />
    <EmbeddedResource Remove="CompilerBackend\bin\**\*" />
    <EmbeddedResource Remove="CompilerBackend\obj\**\*" />
    <EmbeddedResource Remove="AuroraScript.LanguageServices.Tests\**\*" />
    <EmbeddedResource Remove="AuroraScript.LanguageServer.Tests\**\*" />
    <None Remove="bin\**\*" />
    <None Remove="obj\**\*" />
    <None Remove="CompilerBackend\bin\**\*" />
    <None Remove="CompilerBackend\obj\**\*" />
    <None Remove="AuroraScript.LanguageServices.Tests\**\*" />
    <None Remove="AuroraScript.LanguageServer.Tests\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.6.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AuroraScript.csproj" />
    <ProjectReference Include="..\..\language-tools\AuroraScript.Hosting.Generators\AuroraScript.Hosting.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>

</Project>
